### ISSUE TITLE
Path for finding source data should be relative to json schema

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/wp4-converters#1]
Converters now look for CSV files relative to the path of the Python execution, and not relative to the JSON schema that specifies the mapping. This should be fixed

**Comment by kathrinrin** [comment]
Isn't that already solved because the file is supposed to be specified in the .json?  
self._source = dataset['file']

**Comment by RinkeHoekstra** [comment]
No, it is relative to the python module

**Comment by kathrinrin** [comment]
Oh, true, it's fixed!
