### ISSUE TITLE
jinja if-else issue

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-converters#13]
Hi, does anyone understand why:

`"valueUrl": "{% if STATUS == -9 %} http://data.socialhistory.org/resource/hsn2013a/status/{STATUS} {% else %} http://data.socialhistory.org/resource/hisco/status/{STATUS} {% endif %}",`

would result in:

`<http://data.socialhistory.org/resource/hsn2013a/_http:/data.socialhistory.org/resource/hisco/status/-9_>`

**Comment by RinkeHoekstra** [comment]
That's a bug... can fix this in the template.

**Comment by RinkeHoekstra** [comment]
Explanation: the valueUrl is resolved to the base URI *unless* the converter recognises the valueUrl itself as a fully specified URL. This is clearly not the case…

-Rinke

**Comment by RinkeHoekstra** [comment]
CSVW metadata is loaded as JSON-LD, which means that all values of keys are expanded to URIs when appropriate. This happens here as well: the Jinja2 pattern will been prefixed with the default namespace before the converter even sees it. 

A work-around is to use the `null` value to exclude certain values. Could use regexes to extend this even further.

**Comment by RinkeHoekstra** [comment]
Better option: use an xsd:anyURI datatype in combination with a value (rather than valueUrl). This should render the value using Jinja2, and circumvent the automatic base-uri appending of the JSON-LD parser.

**Comment by RinkeHoekstra** [comment]
Documented at <http://csvw-converter.readthedocs.io/en/latest/>
