### ISSUE TITLE
KeyError: u'None' with declaration of skos:definition

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-converters#14]
Hi, I'm trying to add a skos:definition to URI like so:

117     {
118         "virtual": true,
119         "aboutUrl": "http://data.socialhistory.org/resource/hisco/category",
120         "propertyUrl": "skos:definition",
121         "value": "The sub-divisions of occupational unit groups, coded to 5 digits, which provide the finest level of detail in the HISCO classification scheme.",
122         "language": "en"
123     },

However upon conversion I get the following error: 
Traceback (most recent call last):
 File "/Users/RichardZ/git/wp4-converters/src/converter/csvw.py", line 399, in process
   value = row[unicode(c.csvw_name)]
KeyError: u'None'

Could you please look into this?

**Comment by RinkeHoekstra** [comment]
This is most likely due to the converter expecting to see a 'name' attribute if no valueUrl is provided for a virtual column.
