### ISSUE TITLE
is "lang": "en" properly providing language tags?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-converters#16]
Hi, in the file occupation_link.csv-metadata.json in line 186 "lang" is set by a variable and in line 189 by a value. It doesn't appear that the language tags are actually showing up in the .nq files, though.

**Comment by RinkeHoekstra** [comment]
You should use `@lang` not `lang`... but then still the Jinja2 template may not work correctly (as @lang tags are parsed by the JSON-LD parser).

**Comment by rlzijdeman** [comment]
k, will give it a go and report back.
--
Dr. R.L. Zijdeman | CDO | Humanities Cluster: International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

On 2 Feb 2017, at 11:22, Rinke Hoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:


You should use @lang not lang... but then still the Jinja2 template may not work correctly (as @lang<https://github.com/lang> tags are parsed by the JSON-LD parser).

**Comment by rlzijdeman** [comment]
it doesn't work. sorry. see for the update file: ../sdh-private-hisco-datasets/occcupation_link.csv-metadata.json
