### ISSUE TITLE
Null coding doesn't work for date variables

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/wp4-converters#18]
Assigning null values to negative date values (gDay; gMonth; gYear) does not seem to work. Some have values of -2, -4 etc. but the converter does not change them into null values (for example in the BEVSTATP table of HSN). With or without "" doesn't make a difference.

**Comment by RinkeHoekstra** [comment]
Hi @RubenSchalk it would help if you could provide a CSV snippet (just a few lines including headers) + JSON spec that shows the described behaviour.

**Comment by RubenSchalk** [comment]
Hi @RinkeHoekstra, do you have access to gitlab sdh-private-hsn/HSNdbf1000?  There are a couple of CSV's and JSON's where we tried to add nulls for dates and other variable (for instance at BEVDYNAP.DBF.csv-metadata.json and BEVSTATP.DBF.csv-metadata.json).

**Comment by RinkeHoekstra** [comment]
I do, but these files are quite large. Would help if you could just post a few lines here :-)

**Comment by RubenSchalk** [comment]
Here from the BEVSTATP json:
{
    "datatype": "xsd:gDay",
    "titles": [
     "INSDAG"
    ],
    "@id": "http://data.socialhistory.org/resource/BEVSTATP.DBF.csv/column/INSDAG",
    "name": "INSDAG",
    "propertyUrl": "hsn:INSDAG",
    "null": ["-1", "-2", "-4"],
    "dc:description": "Dagnummer start observatieperiode in huishouden"
   },

**Comment by RubenSchalk** [comment]
And here two lines from the corresponding CSV:

"7145","3","714503","6","714503006",,"25","4",,"22",,,"-4","-4","1911",,"49","-4","1917",,"overig",,,"m","-4","-4","1911",,"Utrecht","0","0","0",,,"HSN release 2010.01",
"7145","3","714503","7","714503007",,"26","4",,"22",,,"-4","-4","1913",,"49","-4","1917",,"overig",,,"m","-4","-4","1913",,"Utrecht","0","0","0",,,"HSN release 2010.01",
