### ISSUE TITLE
Converter can’t handle empty variables / column names 

### ISSUE THREAD

**Issue by kathrinrin** [CLARIAH/wp4-converters#2]
http://data.socialhistory.org/ns/resource/variable//{}

=> not clear what to do, maybe adapt csv2qber-schema.py? 
and / or insert some standard value?

**Comment by RinkeHoekstra** [comment]
Indeed, this should be more resilient. Does this hold for qber-output files only? Empty variable names will be problematic for QBer itself as well, as variables are used as keys in the internal datastructure.
